# Generated by Django 4.1.5 on 2023-01-31 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petimage',
            old_name='profile',
            new_name='pet',
        ),
    ]
