# Generated by Django 4.1.5 on 2023-02-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0003_kind_breed_pet_breed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
