# Generated by Django 4.1.5 on 2023-02-02 12:28

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_to),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.upload_to),
        ),
    ]
